### ISSUE TITLE
iot-storage-client additional functionality

### ISSUE THREAD

**Issue by dygonzo** [dgonzo27/py-iot-utils#18]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to be able to perform some additional common Azure Storage operations, but I don't want to subclass this package or write my own.  I'm requesting that these functions are added to the iot-storage-client package.

**Describe the solution you'd like**
New Functions:
1. Copy between containers within the same storage account
2. Move (cut and paste) between containers within the same storage account
3. Download/Copy from a SAS url
4. Generate account SAS url
5. Generate container SAS url
6. Generate blob SAS url

**Describe alternatives you've considered**
I considered sub-classing the package to add this functionality myself, or adopting this code and establishing my own package with the added functionality.  It would be much cleaner to have this available through the existing package.

**To-Do List:**
- [x] copy between containers within the same storage account
- [x] move (cut and paste) between containers within the same storage account
- [x] download/copy from a SAS url
- [x] generate blob SAS URL

**Comment by dgonzo27** [comment]
Thanks @dygonzo - this is in the works!
